'use client'
import { useMemo, useState } from 'react'
import { Calculator, Download, Eye, Filter, Search } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'

type Biz='资源处置'|'资源出租'|'资源采购'|'钢厂直收'
type Record={id:string;biz:Biz;project:string;resource:string;weight:number;distance:number;resourceReduction:number;transportEmission:number;net:number;date:string;status:'已核算'|'待复核'}
const records:Record[]=[
{id:'CAR-202608-0018',biz:'资源处置',project:'报废工装及边角料处置',resource:'废钢',weight:286.4,distance:68,resourceReduction:512.3,transportEmission:1.87,net:510.43,date:'2026-08-19',status:'已核算'},
{id:'CAR-202608-0017',biz:'资源出租',project:'工程钢模板循环租赁',resource:'钢模板',weight:128,distance:36,resourceReduction:149.8,transportEmission:.44,net:149.36,date:'2026-08-18',status:'已核算'},
{id:'CAR-202608-0016',biz:'资源采购',project:'生产辅材集中采购',resource:'热轧钢板',weight:96.5,distance:120,resourceReduction:0,transportEmission:1.11,net:-1.11,date:'2026-08-18',status:'待复核'},
{id:'CAR-202608-0015',biz:'钢厂直收',project:'华南基地废钢竞价回收',resource:'废钢',weight:542.8,distance:188,resourceReduction:971.6,transportEmission:3.24,net:968.36,date:'2026-08-17',status:'已核算'},
{id:'CAR-202608-0014',biz:'钢厂直收',project:'珠江钢厂协议回收',resource:'废钢',weight:860,distance:240,resourceReduction:1539.4,transportEmission:3.72,net:1535.68,date:'2026-08-16',status:'已核算'},
]
const types:Biz[]=['资源处置','资源出租','资源采购','钢厂直收']
export function CarbonAccountingQuery(){const [biz,setBiz]=useState<Biz|'全部'>('全部'),[q,setQ]=useState(''),[detail,setDetail]=useState<Record|null>(null);const visible=useMemo(()=>records.filter(r=>(biz==='全部'||r.biz===biz)&&(r.project+r.resource+r.id).includes(q)),[biz,q]);return <div className="flex flex-col gap-5 p-6">
 <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary"><Calculator className="size-4"/>全业务核算台账</div><h1 className="text-2xl font-semibold tracking-tight">碳核算查询</h1><p className="mt-1 text-sm text-muted-foreground">追溯资源减排、运输排放和净减排结果，核算公式：净减排量 = 资源循环替代减排量 − 运输排放量。</p></div><Button variant="outline"><Download data-icon="inline-start"/>导出核算台账</Button></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{types.map(t=>{const list=records.filter(r=>r.biz===t);return <button key={t} onClick={()=>setBiz(t)} className={`rounded-xl border p-4 text-left transition-colors ${biz===t?'border-primary bg-primary/5':'border-border bg-card hover:border-primary/40'}`}><p className="text-sm text-muted-foreground">{t}</p><p className="mt-2 text-xl font-semibold">{list.reduce((a,b)=>a+b.net,0).toFixed(2)} <span className="text-xs font-normal">tCO₂e</span></p><p className="mt-1 text-xs text-muted-foreground">{list.length} 笔核算记录</p></button>})}</div>
 <Card><CardHeader><CardTitle>核算记录</CardTitle><CardDescription>资源活动数据关联履约重量；运输活动数据按每条陆运、水运物流的吨公里汇总。</CardDescription><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant={biz==='全部'?'default':'outline'} onClick={()=>setBiz('全部')}><Filter data-icon="inline-start"/>全部类型</Button>{types.map(t=><Button key={t} size="sm" variant={biz===t?'default':'outline'} onClick={()=>setBiz(t)}>{t}</Button>)}<div className="relative ml-auto min-w-64"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="项目、资源或核算编号"/></div></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b text-left text-muted-foreground">{['核算编号','业务类型','项目/资源','核算活动数据','资源减排','运输排放','净减排量','状态','操作'].map(x=><th key={x} className="px-3 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-3 py-4 font-mono text-xs">{r.id}<p className="mt-1 text-muted-foreground">{r.date}</p></td><td className="px-3 py-4"><Badge variant="secondary">{r.biz}</Badge></td><td className="px-3 py-4 font-medium">{r.project}<p className="mt-1 text-xs font-normal text-muted-foreground">{r.resource}</p></td><td className="px-3 py-4">{r.weight} t<p className="mt-1 text-xs text-muted-foreground">运输 {r.distance} km</p></td><td className="px-3 py-4 tabular-nums">{r.resourceReduction.toFixed(2)} t</td><td className="px-3 py-4 tabular-nums">{r.transportEmission.toFixed(2)} t</td><td className="px-3 py-4 font-semibold tabular-nums text-primary">{r.net.toFixed(2)} t</td><td className="px-3 py-4"><Badge variant={r.status==='已核算'?'default':'outline'}>{r.status}</Badge></td><td className="px-3 py-4"><Button size="sm" variant="ghost" onClick={()=>setDetail(r)}><Eye data-icon="inline-start"/>追溯</Button></td></tr>)}</tbody></table></div></CardContent></Card>
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>核算结果追溯</DialogTitle><DialogDescription>{detail?.id} · {detail?.project}</DialogDescription></DialogHeader>{detail&&<div className="flex flex-col gap-4"><div className="grid gap-3 sm:grid-cols-3"><Trace label="资源活动数据" value={`${detail.weight} t × 对应资源因子`}/><Trace label="运输活动数据" value={`${detail.weight} t × ${detail.distance} km × 运输因子`}/><Trace label="净减排结果" value={`${detail.net.toFixed(2)} tCO₂e`}/></div><div className="rounded-lg border bg-muted/40 p-4 text-sm leading-6"><b>核算边界：</b>资源回收、再利用或循环使用相对原生材料生产的替代效益，扣除履约中陆运与水运产生的运输排放。<br/><b>数据来源：</b>履约确认重量、物流运输距离、碳因子库有效版本。<br/><b>质量控制：</b>因子版本冻结、活动数据留痕、公式与结果支持复核。</div></div>}</DialogContent></Dialog>
 </div>}
function Trace({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
