'use client'
import { useMemo, useState } from 'react'
import { Database, History, Pencil, Plus, Power, Search } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'

type Factor={id:string;type:'资源因子'|'运输因子';name:string;process:string;value:number;unit:string;source:string;version:string;active:boolean}
const initial:Factor[]=[
{id:'RF-001',type:'资源因子',name:'热轧钢板',process:'高炉—转炉长流程',value:2.18,unit:'tCO₂e/t',source:'中国钢铁工业协会产品碳足迹指南',version:'2026.1',active:true},
{id:'RF-002',type:'资源因子',name:'螺纹钢',process:'电弧炉短流程（废钢）',value:.62,unit:'tCO₂e/t',source:'GB/T 24067-2024 核算原则',version:'2026.1',active:true},
{id:'RF-003',type:'资源因子',name:'冷轧钢卷',process:'高炉—转炉—冷轧',value:2.46,unit:'tCO₂e/t',source:'行业平均值（示例口径）',version:'2025.4',active:true},
{id:'RF-004',type:'资源因子',name:'废钢',process:'回收、分选及预处理',value:.11,unit:'tCO₂e/t',source:'再生钢铁原料行业研究',version:'2026.1',active:true},
{id:'TF-001',type:'运输因子',name:'重型柴油货车',process:'陆运（载重≥20t）',value:.096,unit:'kgCO₂e/(t·km)',source:'交通运输企业温室气体核算指南',version:'2026.1',active:true},
{id:'TF-002',type:'运输因子',name:'内河货船',process:'水运（散货）',value:.018,unit:'kgCO₂e/(t·km)',source:'交通运输行业排放因子（示例）',version:'2026.1',active:true},
]
export function CarbonFactorManagement(){
 const [rows,setRows]=useState(initial),[tab,setTab]=useState<'资源因子'|'运输因子'>('资源因子'),[q,setQ]=useState(''),[editing,setEditing]=useState<Factor|null>(null)
 const visible=useMemo(()=>rows.filter(r=>r.type===tab&&(r.name+r.process+r.source).includes(q)),[rows,tab,q])
 const save=()=>{if(!editing)return;setRows(v=>v.some(x=>x.id===editing.id)?v.map(x=>x.id===editing.id?editing:x):[editing,...v]);setEditing(null)}
 return <div className="flex flex-col gap-5 p-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary"><Database className="size-4"/>碳核算基础数据</div><h1 className="text-2xl font-semibold tracking-tight">碳因子库管理</h1><p className="mt-1 text-sm text-muted-foreground">统一维护钢材资源与陆运、水运因子，记录来源、版本和适用边界。</p></div><Button onClick={()=>setEditing({id:`${tab==='资源因子'?'RF':'TF'}-${String(rows.length+1).padStart(3,'0')}`,type:tab,name:'',process:'',value:0,unit:tab==='资源因子'?'tCO₂e/t':'kgCO₂e/(t·km)',source:'',version:'2026.1',active:true})}><Plus data-icon="inline-start"/>新增{tab}</Button></div>
  <div className="grid gap-4 md:grid-cols-3"><Metric label="资源因子" value={`${rows.filter(r=>r.type==='资源因子').length} 项`} sub="钢材类为主"/><Metric label="运输因子" value={`${rows.filter(r=>r.type==='运输因子').length} 项`} sub="覆盖陆运与水运"/><Metric label="当前有效" value={`${rows.filter(r=>r.active).length} 项`} sub="最新发布版本"/></div>
  <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>因子清单</CardTitle><CardDescription>因子值仅为原型示例，生产环境应以主管部门或经审定数据库为准。</CardDescription></div><div className="flex gap-2"><Button variant={tab==='资源因子'?'default':'outline'} size="sm" onClick={()=>setTab('资源因子')}>资源因子</Button><Button variant={tab==='运输因子'?'default':'outline'} size="sm" onClick={()=>setTab('运输因子')}>运输因子</Button></div></div><div className="relative mt-4 max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索名称、工艺或来源"/></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b text-left text-muted-foreground">{['因子编码','因子名称','适用工艺/运输方式','因子值','来源与版本','状态','操作'].map(x=><th key={x} className="px-3 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-3 py-4 font-mono text-xs">{r.id}</td><td className="px-3 py-4 font-medium">{r.name}</td><td className="px-3 py-4">{r.process}</td><td className="px-3 py-4"><b>{r.value}</b> <span className="text-xs text-muted-foreground">{r.unit}</span></td><td className="max-w-60 px-3 py-4"><p className="truncate">{r.source}</p><p className="mt-1 text-xs text-muted-foreground">版本 {r.version}</p></td><td className="px-3 py-4"><Badge variant={r.active?'default':'secondary'}>{r.active?'启用':'停用'}</Badge></td><td className="px-3 py-4"><div className="flex gap-1"><Button size="icon-sm" variant="ghost" title="编辑" onClick={()=>setEditing(r)}><Pencil/></Button><Button size="icon-sm" variant="ghost" title="版本记录"><History/></Button><Button size="icon-sm" variant="ghost" title={r.active?'停用':'启用'} onClick={()=>setRows(v=>v.map(x=>x.id===r.id?{...x,active:!x.active}:x))}><Power/></Button></div></td></tr>)}</tbody></table></div></CardContent></Card>
  <Dialog open={!!editing} onOpenChange={o=>!o&&setEditing(null)}><DialogContent><DialogHeader><DialogTitle>{editing?.name?'编辑因子':'新增因子'}</DialogTitle><DialogDescription>维护核算因子的适用边界、数值和可信来源。</DialogDescription></DialogHeader>{editing&&<div className="grid gap-3"><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="因子名称"/><Input value={editing.process} onChange={e=>setEditing({...editing,process:e.target.value})} placeholder="适用工艺或运输方式"/><div className="grid grid-cols-2 gap-3"><Input type="number" value={editing.value} onChange={e=>setEditing({...editing,value:Number(e.target.value)})}/><Input value={editing.unit} onChange={e=>setEditing({...editing,unit:e.target.value})}/></div><Input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})} placeholder="来源文件或数据库"/><Input value={editing.version} onChange={e=>setEditing({...editing,version:e.target.value})} placeholder="版本"/></div>}<DialogFooter><Button variant="outline" onClick={()=>setEditing(null)}>取消</Button><Button onClick={save} disabled={!editing?.name}>保存</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <Card><CardHeader className="pb-2"><CardDescription>{label}</CardDescription><CardTitle className="text-2xl">{value}</CardTitle></CardHeader><CardContent className="text-xs text-muted-foreground">{sub}</CardContent></Card>}
