'use client'
import { ArrowUpRight, BarChart3, Download, ExternalLink, Leaf, Recycle, Route, Scale } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, XAxis, YAxis } from 'recharts'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from '@/components/ui/chart'
const trend=[{m:'3月',reduce:1520,transport:42},{m:'4月',reduce:1840,transport:48},{m:'5月',reduce:2210,transport:61},{m:'6月',reduce:2680,transport:73},{m:'7月',reduce:3140,transport:86},{m:'8月',reduce:3920,transport:104}]
const biz=[{name:'资源处置',value:3180},{name:'资源出租',value:1460},{name:'资源采购',value:680},{name:'钢厂直收',value:4720}]
const ranking=[{name:'华南钢铁基地',value:1860},{name:'珠江回收基地',value:1492},{name:'东部制造中心',value:1218},{name:'新港资源公司',value:986},{name:'华中供应链中心',value:742}]
const config={reduce:{label:'资源减排',color:'var(--chart-1)'},transport:{label:'运输排放',color:'var(--chart-3)'},value:{label:'净减排量',color:'var(--chart-2)'}} satisfies ChartConfig
export function CarbonStatistics(){return <div className="flex flex-col gap-5 p-6">
 <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary"><BarChart3 className="size-4"/>碳绩效洞察</div><h1 className="text-2xl font-semibold tracking-tight">统计分析</h1><p className="mt-1 text-sm text-muted-foreground">按业务、资源、组织和时间分析循环资源净减排贡献。</p></div><div className="flex gap-2"><Button variant="outline"><Download data-icon="inline-start"/>导出分析报告</Button><Button onClick={()=>window.open('/carbon-screen','_blank')}><ExternalLink data-icon="inline-start"/>进入数据大屏</Button></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={Leaf} label="累计净减排" value="10,040.26" unit="tCO₂e" change="较上期 +18.6%"/><Kpi icon={Scale} label="循环资源量" value="5,628.4" unit="吨" change="废钢占比 76.8%"/><Kpi icon={Route} label="运输排放" value="414.32" unit="tCO₂e" change="占资源减排 3.96%"/><Kpi icon={Recycle} label="碳核算项目" value="1,286" unit="项" change="本月新增 168 项"/></div>
 <div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><Card><CardHeader><CardTitle>近六个月碳绩效趋势</CardTitle><CardDescription>资源循环替代减排与履约运输排放对比</CardDescription></CardHeader><CardContent><ChartContainer config={config} className="h-72 w-full"><LineChart data={trend}><CartesianGrid vertical={false}/><XAxis dataKey="m" tickLine={false}/><YAxis tickLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Legend/><Line dataKey="reduce" stroke="var(--color-reduce)" strokeWidth={3} dot={false}/><Line dataKey="transport" stroke="var(--color-transport)" strokeWidth={2} dot={false}/></LineChart></ChartContainer></CardContent></Card><Card><CardHeader><CardTitle>业务净减排结构</CardTitle><CardDescription>钢厂直收成为当前最大贡献来源</CardDescription></CardHeader><CardContent><ChartContainer config={config} className="h-72 w-full"><PieChart><ChartTooltip content={<ChartTooltipContent nameKey="name"/>}/><Pie data={biz} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{biz.map((_,i)=><Cell key={i} fill={`var(--chart-${i+1})`}/>)}</Pie><Legend/></PieChart></ChartContainer></CardContent></Card></div>
 <div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]"><Card><CardHeader><CardTitle>组织净减排贡献排行</CardTitle><CardDescription>按已完成并通过复核的项目统计</CardDescription></CardHeader><CardContent><ChartContainer config={config} className="h-72 w-full"><BarChart data={ranking} layout="vertical" margin={{left:24}}><CartesianGrid horizontal={false}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={110} tickLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="value" fill="var(--color-value)" radius={[0,5,5,0]}/></BarChart></ChartContainer></CardContent></Card><Card><CardHeader><CardTitle>数据质量</CardTitle><CardDescription>活动数据和因子引用完整性</CardDescription></CardHeader><CardContent className="flex flex-col gap-5">{[['核算记录完整率','98.7%','1,269 / 1,286'],['有效因子引用率','100%','全部使用有效版本'],['物流数据完整率','96.4%','陆运、水运共 1,842 条'],['待复核记录','17 项','需运营人员处理']].map(([a,b,c])=><div key={a} className="flex items-center justify-between border-b pb-4 last:border-0"><div><p className="text-sm font-medium">{a}</p><p className="mt-1 text-xs text-muted-foreground">{c}</p></div><b className="text-lg text-primary">{b}</b></div>)}</CardContent></Card></div>
 </div>}
function Kpi({icon:Icon,label,value,unit,change}:{icon:typeof Leaf;label:string;value:string;unit:string;change:string}){return <Card><CardHeader className="flex-row items-center justify-between pb-2"><CardDescription>{label}</CardDescription><Icon className="size-4 text-primary"/></CardHeader><CardContent><div className="flex items-baseline gap-1"><b className="text-2xl">{value}</b><span className="text-xs text-muted-foreground">{unit}</span></div><p className="mt-2 flex items-center gap-1 text-xs text-primary"><ArrowUpRight className="size-3"/>{change}</p></CardContent></Card>}
